# Generated by Django 5.0.3 on 2024-03-17 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bicycle', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bicycle',
            name='price',
            field=models.FloatField(),
        ),
    ]
