# Generated by Django 5.0.3 on 2024-03-17 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bicycle', '0002_alter_bicycle_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bicycle',
            name='price',
        ),
        migrations.AddField(
            model_name='bicycletype',
            name='price',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
