# Generated by Django 5.0.3 on 2024-04-01 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usinghistory',
            name='distance',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='usinghistory',
            name='end_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
